### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by aaronurkin** [start-angular/SB-Admin-BS4-Angular-8#302]
Hi,
Packages installation fails with Unexpected end of JSON input while parsing near '...source-map":"latest",' error:
```
...
3971 silly saveTree | `-- @types/chart.js@2.9.19
3971 silly saveTree +-- protractor@5.4.3
3971 silly saveTree +-- rxjs@6.5.4
3971 silly saveTree +-- ts-node@8.6.2
3971 silly saveTree +-- tslib@1.11.1
3971 silly saveTree +-- tslint@6.0.0
3971 silly saveTree +-- yarn@1.22.0
3971 silly saveTree `-- zone.js@0.10.3
3972 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...source-map":"latest",'
3972 verbose stack     at JSON.parse (<anonymous>)
3972 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
3972 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
3972 verbose stack     at runMicrotasks (<anonymous>)
3972 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
3973 verbose cwd d:\source\SB-Admin-BS4-Angular-8-master
3974 verbose Windows_NT 10.0.18362
3975 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
3976 verbose node v12.16.2
3977 verbose npm  v6.14.4
3978 error Unexpected end of JSON input while parsing near '...source-map":"latest",'
3979 verbose exit [ 1, true ]
```

**Comment by aaronurkin** [comment]
Resolved:
Run Command Promt as administrator
Run: `npm cache clean --force`
